# Generated by Django 3.2.6 on 2021-08-12 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeterDataRead',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_time_date', models.CharField(blank=True, max_length=100, null=True)),
                ('hex', models.CharField(blank=True, max_length=100, null=True)),
                ('kwh', models.CharField(blank=True, max_length=100, null=True)),
                ('kwh2', models.CharField(blank=True, max_length=100, null=True)),
                ('kvarh', models.CharField(blank=True, max_length=100, null=True)),
                ('kvarh2', models.CharField(blank=True, max_length=100, null=True)),
                ('kvah', models.CharField(blank=True, max_length=100, null=True)),
                ('avah2', models.CharField(blank=True, max_length=100, null=True)),
                ('voltage1', models.CharField(blank=True, max_length=100, null=True)),
                ('voltage2', models.CharField(blank=True, max_length=100, null=True)),
                ('voltage3', models.CharField(blank=True, max_length=100, null=True)),
                ('current1', models.CharField(blank=True, max_length=100, null=True)),
                ('current2', models.CharField(blank=True, max_length=100, null=True)),
                ('current3', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
