# Generated by Django 3.2.6 on 2021-08-12 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infoapp', '0002_auto_20210812_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meterdataread',
            name='feeder',
        ),
        migrations.RemoveField(
            model_name='meterdataread',
            name='month',
        ),
        migrations.RemoveField(
            model_name='meterdataread',
            name='substation',
        ),
        migrations.RemoveField(
            model_name='meterdataread',
            name='year',
        ),
    ]
